import {useEffect,useState} from "react";import Layout from "../components/Layout";import Modal from "../components/Modal";import Toast from "../components/Toast";import Loading from "../components/Loading";import {del,get,post,put} from "../lib/api";import {formatDate} from "../lib/utils";import {getUser} from "../lib/auth";
const blank={title:"",description:"",status:"pending",deadline:"",member_ids:[]};
export default function Assignments(){const user=getUser(),admin=user?.role==="admin";const[items,setItems]=useState([]),[members,setMembers]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[toast,setToast]=useState("");
async function load(){setLoading(true);try{const[a,u]=await Promise.all([get("/api/assignments"),admin?get("/api/users?role=member"):Promise.resolve({users:[]})]);setItems(a.assignments);setMembers(u.users)}catch(e){setToast(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
const change=e=>setForm({...form,[e.target.name]:e.target.value});const toggle=id=>setForm(f=>({...f,member_ids:f.member_ids.includes(id)?f.member_ids.filter(x=>x!==id):[...f.member_ids,id]}));
async function submit(e){e.preventDefault();try{const p={...form,deadline:form.deadline||null};if(editing)await put(`/api/assignments/${editing}`,p);else await post("/api/assignments",p);setOpen(false);setEditing(null);setForm(blank);setToast("Assignment saved and assignees notified.");load()}catch(e){setToast(e.message)}}
function edit(x){setEditing(x.id);setForm({title:x.title,description:x.description||"",status:x.status,deadline:x.deadline?x.deadline.slice(0,16):"",member_ids:(x.members||[]).map(m=>m.id)});setOpen(true)}async function remove(id){if(!confirm("Delete this assignment?"))return;try{await del(`/api/assignments/${id}`);setToast("Assignment deleted.");load()}catch(e){setToast(e.message)}}
return <Layout><div className="page-heading"><div><p className="eyebrow">{admin?"WORKSTREAMS / CONTROL":"MY WORKSPACE"}</p><h2>{admin?"Assignments":"My Assignments"}</h2><p className="page-subtitle">{admin?"Assign one assignment to multiple members with full instructions.":"Your assigned work is shown here with the complete brief, deadline, assignees and latest update."}</p></div>{admin&&<button className="primary-btn" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}>+ New Assignment</button>}</div>{loading?<Loading/>:<div className="card-grid">{items.length===0?<div className="panel empty">{admin ? "No assignments created yet." : "No assignments assigned to you yet."}</div>:items.map(x=><article className="work-card detail-card" key={x.id}><div className="card-top"><span className={`tag tag-${x.status}`}>{x.status.replace("_"," ")}</span><span>ASSIGNMENT #{x.id}</span></div><h3>{x.title}</h3><p className="detail-description">{x.description||"No additional brief provided."}</p><div className="detail-grid"><div><span>DEADLINE</span><b>{formatDate(x.deadline)}</b></div><div><span>ASSIGNED MEMBERS</span><b>{(x.members||[]).map(m=>m.name).join(", ")||"You"}</b></div><div><span>CREATED</span><b>{formatDate(x.created_at)}</b></div><div><span>LAST UPDATED</span><b>{formatDate(x.updated_at)}</b></div></div>{admin&&<div className="card-actions"><button onClick={()=>edit(x)}>Edit</button><button className="danger-text" onClick={()=>remove(x.id)}>Delete</button></div>}</article>)}</div>}
<Modal open={open} title={editing?"Edit Assignment":"Create Assignment"} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><label>Title<input name="title" value={form.title} onChange={change} required/></label><label>Full assignment brief<textarea name="description" value={form.description} onChange={change} rows="6" placeholder="Requirements, deliverables, submission instructions, resources..."/></label><div className="form-grid"><label>Status<select name="status" value={form.status} onChange={change}><option>pending</option><option>in_progress</option><option>completed</option></select></label><label>Deadline<input type="datetime-local" name="deadline" value={form.deadline} onChange={change}/></label></div><div className="picker"><div className="picker-title">Assign to multiple members</div>{members.map(m=><label className="member-option" key={m.id}><input type="checkbox" checked={form.member_ids.includes(m.id)} onChange={()=>toggle(m.id)}/><span><b>{m.name}</b><small>{m.id}</small></span></label>)}</div><button className="primary-btn full">{editing?"Update Assignment":"Create & Assign"}</button></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></Layout>}
