import {useEffect,useState} from "react";import Layout from "../components/Layout";import Modal from "../components/Modal";import Toast from "../components/Toast";import Loading from "../components/Loading";import {del,get,post,put} from "../lib/api";import {formatDate} from "../lib/utils";import {getUser} from "../lib/auth";
const blank={name:"",description:"",status:"upcoming",event_date:"",team_info:"",member_ids:[]};
export default function Hackathons(){const user=getUser(),admin=user?.role==="admin";const[items,setItems]=useState([]),[members,setMembers]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[toast,setToast]=useState("");
async function load(){setLoading(true);try{const[h,u]=await Promise.all([get("/api/hackathons"),admin?get("/api/users?role=member"):Promise.resolve({users:[]})]);setItems(h.hackathons);setMembers(u.users)}catch(e){setToast(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
const change=e=>setForm({...form,[e.target.name]:e.target.value});const toggle=id=>setForm(f=>({...f,member_ids:f.member_ids.includes(id)?f.member_ids.filter(x=>x!==id):[...f.member_ids,id]}));
async function submit(e){e.preventDefault();try{const p={...form,event_date:form.event_date||null};if(editing)await put(`/api/hackathons/${editing}`,p);else await post("/api/hackathons",p);setOpen(false);setEditing(null);setForm(blank);setToast("Hackathon saved and members notified.");load()}catch(e){setToast(e.message)}}
function edit(x){setEditing(x.id);setForm({name:x.name,description:x.description||"",status:x.status,event_date:x.event_date?x.event_date.slice(0,16):"",team_info:x.team_info||"",member_ids:(x.members||[]).map(m=>m.id)});setOpen(true)}async function remove(id){if(!confirm("Delete this hackathon?"))return;try{await del(`/api/hackathons/${id}`);setToast("Hackathon deleted.");load()}catch(e){setToast(e.message)}}
return <Layout><div className="page-heading"><div><p className="eyebrow">{admin?"EVENTS / CONTROL":"MY WORKSPACE"}</p><h2>{admin?"Hackathons":"My Hackathons"}</h2><p className="page-subtitle">{admin?"Assign hackathons to multiple members and keep event details synchronized.":"Only hackathons assigned to you are shown, including event, team and latest update details."}</p></div>{admin&&<button className="primary-btn" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}>+ New Hackathon</button>}</div>{loading?<Loading/>:<div className="card-grid">{items.length===0?<div className="panel empty">{admin ? "No hackathons created yet." : "No hackathons assigned to you yet."}</div>:items.map(x=><article className="work-card detail-card" key={x.id}><div className="card-top"><span className={`tag tag-${x.status}`}>{x.status}</span><span>HACKATHON #{x.id}</span></div><h3>{x.name}</h3><p className="detail-description">{x.description||"No event description provided."}</p><div className="event-date">◷ {formatDate(x.event_date)}</div>{x.team_info&&<div className="team-info"><strong>TEAM / EVENT NOTES</strong><br/>{x.team_info}</div>}<div className="detail-grid"><div><span>ASSIGNED MEMBERS</span><b>{(x.members||[]).map(m=>m.name).join(", ")||"You"}</b></div><div><span>CREATED</span><b>{formatDate(x.created_at)}</b></div><div><span>LAST UPDATED</span><b>{formatDate(x.updated_at)}</b></div></div>{admin&&<div className="card-actions"><button onClick={()=>edit(x)}>Edit</button><button className="danger-text" onClick={()=>remove(x.id)}>Delete</button></div>}</article>)}</div>}
<Modal open={open} title={editing?"Edit Hackathon":"Create Hackathon"} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><label>Hackathon name<input name="name" value={form.name} onChange={change} required/></label><label>Full event details<textarea name="description" value={form.description} onChange={change} rows="5" placeholder="Problem statement, rules, deliverables, links, venue..."/></label><div className="form-grid"><label>Status<select name="status" value={form.status} onChange={change}><option>upcoming</option><option>active</option><option>completed</option></select></label><label>Event date<input type="datetime-local" name="event_date" value={form.event_date} onChange={change}/></label></div><label>Team / Member information<textarea name="team_info" value={form.team_info} onChange={change} rows="4" placeholder="Team name, role, mentor, submission details..."/></label><div className="picker"><div className="picker-title">Assign to multiple members</div>{members.map(m=><label className="member-option" key={m.id}><input type="checkbox" checked={form.member_ids.includes(m.id)} onChange={()=>toggle(m.id)}/><span><b>{m.name}</b><small>{m.id}</small></span></label>)}</div><button className="primary-btn full">{editing?"Update Hackathon":"Create & Assign"}</button></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></Layout>}
