import { useEffect,useState } from "react";
import Layout from "../components/Layout"; import Modal from "../components/Modal"; import Toast from "../components/Toast"; import Loading from "../components/Loading";
import {del,get,post,put} from "../lib/api"; import {formatDate} from "../lib/utils"; import {getUser} from "../lib/auth";
const blank={title:"",description:"",status:"todo",priority:"medium",deadline:"",assignee_ids:[]};
export default function Tasks(){
 const user=getUser(),admin=user?.role==="admin"; const [tasks,setTasks]=useState([]),[members,setMembers]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[toast,setToast]=useState("");
 async function load(){setLoading(true);try{const r=await Promise.all([get("/api/tasks"),admin?get("/api/users?role=member"):Promise.resolve({users:[]})]);setTasks(r[0].tasks);setMembers(r[1].users)}catch(e){setToast(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const toggle=id=>setForm(f=>({...f,assignee_ids:f.assignee_ids.includes(id)?f.assignee_ids.filter(x=>x!==id):[...f.assignee_ids,id]}));
 async function submit(e){e.preventDefault();try{const p={...form,deadline:form.deadline||null};if(editing)await put(`/api/tasks/${editing}`,p);else await post("/api/tasks",p);setOpen(false);setEditing(null);setForm(blank);setToast("Task saved and assignees notified.");load()}catch(e){setToast(e.message)}}
 function edit(t){setEditing(t.id);setForm({title:t.title,description:t.description||"",status:t.status,priority:t.priority,deadline:t.deadline?t.deadline.slice(0,16):"",assignee_ids:(t.assignees||[]).map(x=>x.id)});setOpen(true)}
 async function remove(id){if(!confirm("Delete this task?"))return;try{await del(`/api/tasks/${id}`);setToast("Task deleted.");load()}catch(e){setToast(e.message)}}
 return <Layout><div className="page-heading"><div><p className="eyebrow">{admin?"OPERATIONS / CONTROL":"MY WORKSPACE"}</p><h2>{admin?"Task Control":"My Tasks"}</h2><p className="page-subtitle">{admin?"Assign one task to multiple members and keep every update visible.":"Only tasks assigned to you are shown here, with complete instructions, priority, deadline and assignees."}</p></div>{admin&&<button className="primary-btn" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}>+ New Task</button>}</div>
 {loading?<Loading/>:<div className="card-grid">{tasks.length===0?<div className="panel empty">{admin ? "No tasks created yet." : "No tasks assigned to you yet."}</div>:tasks.map(t=><article className="work-card detail-card" key={t.id}><div className="card-top"><span className={`tag tag-${t.status}`}>{t.status.replace("_"," ")}</span><span className={`priority priority-${t.priority}`}>{t.priority}</span></div><h3>{t.title}</h3><p className="detail-description">{t.description||"No additional instructions provided."}</p><div className="detail-grid"><div><span>DEADLINE</span><b>{formatDate(t.deadline)}</b></div><div><span>ASSIGNED TO</span><b>{(t.assignees||[]).map(x=>x.name).join(", ")||"You"}</b></div><div><span>CREATED</span><b>{formatDate(t.created_at)}</b></div><div><span>LAST UPDATED</span><b>{formatDate(t.updated_at)}</b></div></div>{admin&&<div className="card-actions"><button onClick={()=>edit(t)}>Edit</button><button className="danger-text" onClick={()=>remove(t.id)}>Delete</button></div>}</article>)}</div>}
 <Modal open={open} title={editing?"Edit Task":"Create Task"} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><label>Title<input name="title" value={form.title} onChange={change} required/></label><label>Full task details<textarea name="description" value={form.description} onChange={change} rows="5" placeholder="Instructions, deliverables, resources, acceptance criteria..."/></label><div className="form-grid"><label>Status<select name="status" value={form.status} onChange={change}><option value="todo">To Do</option><option value="in_progress">In Progress</option><option value="done">Done</option></select></label><label>Priority<select name="priority" value={form.priority} onChange={change}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label></div><label>Deadline<input type="datetime-local" name="deadline" value={form.deadline} onChange={change}/></label><div className="picker"><div className="picker-title">Assign to multiple members</div>{members.map(m=><label className="member-option" key={m.id}><input type="checkbox" checked={form.assignee_ids.includes(m.id)} onChange={()=>toggle(m.id)}/><span><b>{m.name}</b><small>{m.id}</small></span></label>)}</div><button className="primary-btn full">{editing?"Update Task":"Create & Assign Task"}</button></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></Layout>}
